# User Config
sonata_user:
    security_acl: true
    #admin:
    #    user:
    #        class:      TactDory\CoreBundle\Admin\UserAdmin
    #        controller: TactDoryCoreBundle:UserAdmin
    profile:  # Profile Form (firstname, lastname, etc ...)
        form:
            type:               sonata_user_profile
            handler:            sonata.user.profile.form.handler.default
            name:               sonata_user_profile_form
            validation_groups:  [Profile]
    admin:
        user:
          class: Tact\DoryBundle\Admin\Model\UserAdmin

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
        sonata.block.service.rss:
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes
        sonata.block.service.action:

sonata_intl:
    timezone:
        locales:
            fr:    Europe/Paris
            en_UK: Europe/London
        detectors:
            - sonata.intl.timezone_detector.user ## Need fosuser.
            #- sonata.intl.timezone_detector.locale ## Default.
        default: Europe/Paris
