rms_push_notifications:
  android:
      # c2dm is deprecated since june 2012
      # c2dm:
      #    username: "user" # <string_android_c2dm_username>
      #    password: "pass" # <string_android_c2dm_password>
      #    source: "app"    # <string_android_c2dm_source>
      gcm:
          api_key: "xxx" # <string_android_gcm_api_key>
          use_multi_curl: false  # <boolean_android_gcm_use_multi_curl> default is true
#  ios:
#      sandbox: true             # <bool_use_apns_sandbox>
#      pem: "%kernel.root_dir%/../tact-dory.pem"          # <path_apns_certificate> # can be absolute or relative path (from app directory)
#      passphrase: "tact_dory_pass"   # <string_apns_certificate_passphrase>
#  mac:
#      sandbox: false            # <bool_use_apns_sandbox>
#      pem: "%kernel.root_dir%/../tact-dory.pem"          # <path_apns_certificate>
#      passphrase: "tact_dory_pass"   # <string_apns_certificate_passphrase>
#  blackberry:
#      evaluation: true          # <bool_bb_evaluation_mode>
#      app_id: "tact_dory_app"        # <string_bb_app_id>
#      password: "tact_dory_pass"     # <string_bb_password>
