bazinga_geocoder:
    fake_ip:
        enabled:              true
        ip:                   77.131.27.176
        priority:             1
#    adapter:                    ~ # An adapter service id
    default_provider:         openstreetmap # Name of provider, e.g. chain
    providers:
#        bing_maps:
#            api_key:              ~ # Required
#            locale:               null
#        cache:
#            adapter:              ~ # Required
#            provider:             ~ # Required
#            locale:               null
#            lifetime:             86400
#        ip_info_db:
#            api_key:              ~ # Required
        google_maps:
            locale:               null
            region:               null
            use_ssl:              false
            api_key:              null
#        google_maps_business:
#            client_id:            ~ # Required
#            api_key:              null
#            locale:               null
#            region:               null
#            use_ssl:              false
        openstreetmap:
            locale:               null
#        host_ip:              []
        geoip:                []
#        free_geo_ip:          []
#        mapquest:
#            api_key:              ~ # Required
#        yandex:
#            locale:               null
#            toponym:              null
#        geo_ips:
#            api_key:              null
#        geo_plugin:           []
#        maxmind:
#            api_key:              ~ # Required
#        maxmind_binary:
#            binary_file:          ~ # Required
#            open_flag:            null
#        opencage:
#            locale:               null
#            use_ssl:              false
#            api_key:              null
#        chain:
#            providers:            []
#        tom_tom:
#            api_key:              ~ # Required
#            locale:               null