## The Dory rules generalisation about the test execution.
framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

liip_functional_test: ~

doctrine:
    dbal:
        driver:   pdo_sqlite
        user:   test
        path:   '%kernel.root_dir%/sqlite.db.cache'
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        entity_managers:
            default:
                metadata_cache_driver: apcu
                query_cache_driver:    apcu
                result_cache_driver:   apcu
