imports:
    - { resource: ../../../../../app/config/parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: bdl_fosuser.yml }
    - { resource: bdl_session.yml }
    - { resource: bdl_fosrest.yml }
    - { resource: bdl_migrate.yml }
    - { resource: bdl_sonata.yml }
    - { resource: bdl_nelmioapi.yml }
    - { resource: bdl_paginator.yml }
    - { resource: bdl_filter.yml }
    - { resource: bdl_intl.yml }
    - { resource: bdl_gravatar.yml }
    - { resource: bdl_files.yml }
    - { resource: bdl_maintenance.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: [10.10.100.0/24]
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  session.handler.pdo
        cookie_lifetime: 604800
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'SonataCoreBundle:Form:datepicker.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "pdo_%database_type%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: 5.6
        mapping_types:
            enum: string
        types:
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
