services:
    app.form.type.boolean:
        class: Tact\DoryBundle\Form\BooleanType
        tags:
            - { name: form.type, alias: boolean }
    dory.model.mailer:
        class: Tact\DoryBundle\Models\MailEngine
        calls:
            - [ setContainer, [ '@service_container' ] ]
