# Routes about locals projects.. 
################################################################################

tact_front:
    resource: "@TactFrontBundle/Controller/"
    type:     annotation
    prefix:   /

tact_probe:
    resource: "@TactProbeBundle/Controller/"
    type:     annotation
    prefix:   /api

tact_ota:
    resource: "@TactOtaBundle/Controller/"
    type:     annotation
    prefix:   /ota

# Dory (define default routes about Sonata:User, Sonata:admin, Nemlio:Api. 
################################################################################

dory: 
    resource: "@TactDoryBundle/Resources/config/routing.yml"
    prefix: /
