# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html

security:

## Default parameters from Dory. All its options are overridable except the following.
    access_control:
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/api/*, role: IS_AUTHENTICATED_ANONYMOUSLY } #ROLE_API

        - { path: ^/(.+), roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_SUPER_ADMIN:
            - ROLE_ESOFTLINK_ADMIN

        ROLE_ESOFTLINK_ADMIN: # Group admin.
            #- ROLE_SUPER_ADMIN
            - ROLE_ESOFTLINK_MANAGER 
            - ROLE_ESOFTLINK_GROUP_MANAGER
            - ROLE_ESOFTLINK_CUSTOM_DATABASE_QUERY

        ROLE_ESOFTLINK_MANAGER: # Group Manager.
            - SONATA
            - ROLE_ADMIN
            - ROLE_SONATA_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_ESOFTLINK_USER_MANAGER
            - ROLE_ESOFTLINK_PROBE_MANAGER
            - ROLE_ESOFTLINK_SUBSCRIPTION_MANAGER
            - ROLE_ESOFTLINK_API
            - ROLE_ESOFTLINK_PRICE
            - ROLE_TACT_PROBE_ADMIN_LOG

        ROLE_ESOFTLINK_USER:
            - ROLE_ESOFTLINK_INSTALLATION_MANAGER
            - ROLE_ESOFTLINK_ERL_STATUS_MANAGER
            - ROLE_ESOFTLINK_WIFI_MANAGER

        ROLE_ESOFTLINK_USER_MANAGER:
            - ROLE_SONATA_USER_ADMIN_USER_CREATE
            - ROLE_SONATA_USER_ADMIN_USER_DELETE
            - ROLE_SONATA_USER_ADMIN_USER_LIST
            - ROLE_SONATA_USER_ADMIN_USER_VIEW
            - ROLE_SONATA_USER_ADMIN_USER_EXPORT
            - ROLE_SONATA_USER_ADMIN_USER_MASTER
            - ROLE_SONATA_USER_ADMIN_USER_VIEW
            - ROLE_SONATA_USER_ADMIN_USER_OPERATOR
            - ROLE_SONATA_USER_ADMIN_USER_EDIT

        ROLE_ESOFTLINK_GROUP_MANAGER:
            - ROLE_SONATA_USER_ADMIN_GROUP_CREATE
            - ROLE_SONATA_USER_ADMIN_GROUP_DELETE
            - ROLE_SONATA_USER_ADMIN_GROUP_LIST
            - ROLE_SONATA_USER_ADMIN_GROUP_VIEW
            - ROLE_SONATA_USER_ADMIN_GROUP_EXPORT
            - ROLE_SONATA_USER_ADMIN_GROUP_MASTER
            - ROLE_SONATA_USER_ADMIN_GROUP_VIEW
            - ROLE_SONATA_USER_ADMIN_GROUP_OPERATOR
            - ROLE_SONATA_USER_ADMIN_GROUP_EDIT

        ROLE_ESOFTLINK_PROBE_MANAGER:
            - ROLE_TACT_CORE_ADMIN_PROBE_CREATE
            - ROLE_TACT_CORE_ADMIN_PROBE_DELETE
            - ROLE_TACT_CORE_ADMIN_PROBE_LIST
            - ROLE_TACT_CORE_ADMIN_PROBE_VIEW
            - ROLE_TACT_CORE_ADMIN_PROBE_EXPORT
            - ROLE_TACT_CORE_ADMIN_PROBE_MASTER
            - ROLE_TACT_CORE_ADMIN_PROBE_VIEW
            - ROLE_TACT_CORE_ADMIN_PROBE_OPERATOR
            - ROLE_TACT_CORE_ADMIN_PROBE_EDIT

        ROLE_ESOFTLINK_SUBSCRIPTION_MANAGER:
            - ROLE_TACT_CORE_ADMIN_SUBSCRIPTION_CREATE
            - ROLE_TACT_CORE_ADMIN_SUBSCRIPTION_DELETE
            - ROLE_TACT_CORE_ADMIN_SUBSCRIPTION_LIST
            - ROLE_TACT_CORE_ADMIN_SUBSCRIPTION_VIEW
            - ROLE_TACT_CORE_ADMIN_SUBSCRIPTION_EXPORT
            - ROLE_TACT_CORE_ADMIN_SUBSCRIPTION_MASTER
            - ROLE_TACT_CORE_ADMIN_SUBSCRIPTION_VIEW
            - ROLE_TACT_CORE_ADMIN_SUBSCRIPTION_OPERATOR
            - ROLE_TACT_CORE_ADMIN_SUBSCRIPTION_EDIT

        ROLE_TACT_PROBE_ADMIN_LOG:
            #- ROLE_TACT_PROBE_ADMIN_LOG_CREATE
            - ROLE_TACT_PROBE_ADMIN_LOG_DELETE
            - ROLE_TACT_PROBE_ADMIN_LOG_LIST
            #- ROLE_TACT_PROBE_ADMIN_LOG_VIEW
            #- ROLE_TACT_PROBE_ADMIN_LOG_EXPORT
            #- ROLE_TACT_PROBE_ADMIN_LOG_MASTER
            #- ROLE_TACT_PROBE_ADMIN_LOG_VIEW
            #- ROLE_TACT_PROBE_ADMIN_LOG_OPERATOR
            #- ROLE_TACT_PROBE_ADMIN_LOG_EDIT
